---
language: python
python: "2.7"

sudo: required

install:
  - pip install ansible apt
  - ansible --version

script:
  - echo -ne '[cimon-ansible]\nlocalhost ansible_connection=local ansible_python_interpreter=' > inventory
  - which python >> inventory
  - ansible-playbook tests/playbook.yml -i inventory --syntax-check
  - ansible-playbook tests/playbook.yml -i inventory
  - >
    ansible-playbook tests/playbook.yml -i inventory 
    | grep -q 'changed=0.*failed=0' 
    && (echo 'Idempotence test: pass' && exit 0) 
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
