---
- name: "install software required for nginx"
  apt:
    name: "{{ nginx_requirements }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  retries: "{{ remote_package_retries }}"
  register: apt_deps_result
  until: apt_deps_result is succeeded

- name: "add nginx repo key"
  apt_key:
    url: "{{ nginx_key }}"

- name: "add nginx repository"
  template:
    src: "etc/apt/sources.list.d/nginx.list.j2"
    dest: "/etc/apt/sources.list.d/nginx.list"
    owner: root

- name: "pin nginx repository"
  template:
    src: "etc/apt/preferences.d/nginx.pref.j2"
    dest: "/etc/apt/preferences.d/nginx.pref"
    owner: root

- name: "install nginx"
  apt:
    name: "nginx={{ nginx_version }}*"
    state: present
    update_cache: true
    cache_valid_time: 0
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded

- name: "create sites directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"

- name: "install certbot"
  git:
    repo: "https://github.com/certbot/certbot.git"
    dest: /opt/certbot
    update: no
  when: nginx_letsencrypt_sites|bool

- name: "install requirements for certbot"
  shell: "./certbot-auto -n --os-packages-only"
  args:
    chdir: /opt/certbot
    executable: /bin/bash
  when: nginx_letsencrypt_sites|bool
