---
- name: "install software required for nginx"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items: "{{ nginx_requirements }}"

- name: "add nginx repo key"
  apt_key:
    url: "{{ nginx_key }}"

- name: "add nginx repository"
  apt_repository:
    repo: "{{ nginx_repo }}"
    filename: "nginx"

- name: "pin nginx repository"
  template:
    src: "etc/apt/preferences.d/nginx.pref.j2"
    dest: "/etc/apt/preferences.d/nginx.pref"
    owner: root

- name: "install nginx"
  apt:
    name: "nginx={{ nginx_version }}*"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: "create sites directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"

- name: "install certbot"
  git:
    repo: "https://github.com/certbot/certbot.git"
    dest: /opt/certbot
    version: "{{ nginx_certbot_version }}"
  when: nginx_letsencrypt_sites

- name: "install requirements for certbot"
  shell: "./certbot-auto -n --os-packages-only"
  args:
    chdir: /opt/certbot
    executable: /bin/bash
  when: nginx_letsencrypt_sites
