---
# Generate Let's Encrypt SSL
- name: "create letsencrypt directory"
  file:
    name: "{{ nginx_wellknown_path }}"
    state: directory

- name: "get ssl"
  shell: "./certbot-auto certonly -n --webroot -w {{ nginx_wellknown_path }} --domains {{ nginx_sites[item].server_name | join(',') }} --email admin@{{ nginx_sites[item].server_name[0] }} --agree-tos --expand --keep-until-expiring --allow-subset-of-names --cert-name {{ item }} --post-hook 'nginx -s reload' 2>&1"
  args:
    chdir: /opt/certbot
    executable: /bin/bash
  with_items: "{{ nginx_letsencrypt_sites }}"

- name: "link ssl cert"
  file:
    path: "{{ nginx_ssl_path }}/{{ item }}.crt"
    src: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
    state: link
  with_items: "{{ nginx_letsencrypt_sites }}"

- name: "link ssl key"
  file:
    path: "{{ nginx_ssl_path }}/{{ item }}.key"
    src: "/etc/letsencrypt/live/{{ item }}/privkey.pem"
    state: link
  with_items: "{{ nginx_letsencrypt_sites }}"

- name: "set crontask - ssl renewal"
  cron:
    name: "update letsencrypt SSL"
    hour: 5
    minute: 15
    weekday: 1
    job: "/opt/certbot/certbot-auto renew --agree-tos"
  when: nginx_letsencrypt_sites
