---
- name: "include config files"
  include_vars: "{{ item }}"
  with_items:
    - ssl.yml
    - configure.yml
    - install.yml
  tags: [nginx, nginx-apt, nginx-config]

- name: "install nginx"
  include: install.yml
  tags: [nginx, nginx-apt]

- name: "configure nginx"
  include: configure.yml
  tags: [nginx, nginx-config]

- name: "site ssl configuration"
  include: ssl.yml
  tags: [nginx, nginx-config, nginx-site, nginx-ssl]

- name: "letsencrypt ssl configuration"
  include: letsencrypt.yml
  tags: [nginx, nginx-config, nginx-site, nginx-ssl]

- name: "configure nginx sites"
  include: configure_site.yml
  tags: [nginx, nginx-config, nginx-site]

- meta: flush_handlers
