FROM ubuntu:16.04

RUN apt-get update -qq && \
    apt-get install -qq sudo python-apt python-pycurl python-pip python-dev \
                        python-passlib libffi-dev && \
    pip install -U setuptools && \
    pip install -q ansible==2.6.4

    WORKDIR /tmp/ansible-role-nginx
    COPY  .  /tmp/ansible-role-nginx

    RUN echo "localhost" > inventory
    RUN ansible-playbook -i inventory -c local tests/playbook.yml --syntax-check
    RUN ansible-playbook -i inventory -c local tests/playbook.yml

