---
# https://nginx.org/en/docs/http/ngx_http_core_module.html
nginx_user: "www-data"
nginx_worker_processes: "auto"
nginx_worker_connections: "768"
nginx_multi_accept: "off"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: "65"
nginx_types_hash_max_size: "2048"
nginx_server_names_hash_bucket_size: "64"

# https://nginx.org/en/docs/http/ngx_http_gzip_module.html
nginx_gzip: "on"
nginx_gzip_comp_level: "6"
nginx_gzip_types: "text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript"

# https://nginx.org/en/docs/http/ngx_http_log_module.html
nginx_log_format: {}
# name: combined
# string: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
